compute:
  hosts:
    node0:
      ansible_host: onana@clnode185.clemson.cloudlab.us
  vars:
    ansible_user: onana

storage:
  hosts:
    node0:
      ansible_host: onana@clnode185.clemson.cloudlab.us
  vars:
    ansible_user: onana



#  onana@clnode185.clemson.cloudlab.us
#  onana@clnode201.clemson.cloudlab.us

# scp -r onana@clnode185.clemson.cloudlab.us:/users/onana/benchmark/ ./