compute:
  hosts:
    node0:
      ansible_host: onana@apt129.apt.emulab.net
    node1:
      ansible_host: onana@apt130.apt.emulab.net
    node2:
      ansible_host: onana@apt131.apt.emulab.net
    
  vars:
    ansible_user: onana

controller:
  hosts:
    node0:
      ansible_host: onana@apt129.apt.emulab.net
  vars:
    ansible_user: onana

storage:
  hosts:
    node0:
      ansible_host: onana@apt129.apt.emulab.net
  vars:
    ansible_user: onana


# ssh onana@apt129.apt.emulab.net

# scp -r onana@apt174.apt.emulab.net:/users/onana/benchmark/text-to-speech/result ./
# ssh onana@apt139.apt.emulab.net

# ssh onana@apt174.apt.emulab.net
 